### ISSUE TITLE
Número de teléfono

### ISSUE THREAD

**Issue by terroneser** [AlejandroG1/codewordapi#5]
Validación del número de teléfono en modelo de usuarios y booking
![image](https://user-images.githubusercontent.com/55569792/158430921-d2bb1446-bef1-43f4-bae6-591bc32a63bf.png)
![image](https://user-images.githubusercontent.com/55569792/158431153-63d9ad71-9b19-4b32-a32e-8d89ad9c7948.png)

**Comment by CristianMeSu** [comment]
Por que pide un numero menor a ese? tenemos que usar una variable mas grande no?
