### ISSUE TITLE
Modificación de módulo de usuario

### ISSUE THREAD

**Issue by terroneser** [AlejandroG1/codewordapi#8]
- [x] Agregar campo de contraseña
- [x] Agregar campo de username

**Comment by terroneser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Modificación de módulo de usuario](https://trello.com/c/EzGLBB7I/47-modificaci%C3%B3n-de-m%C3%B3dulo-de-usuario)

**Comment by CristianMeSu** [comment]
Ya aparecen las tablas nuevas, excelente
