### ISSUE TITLE
Mejorar seguridad para el acceso del API

### ISSUE THREAD

**Issue by AlejandroG1** [AlejandroG1/codewordapi#9]
Cambiar la seguridad de TOKEN por una mediante JWT (Json Web Token)

**Comment by terroneser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mejorar seguridad para el acceso del API](https://trello.com/c/GNaM90h5/49-mejorar-seguridad-para-el-acceso-del-api)
